spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  redis:
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: Z2RzYy1za2h1LWphdmEtYmFja2VuZC1qd3Qtc3R1ZHktZGVjZW1iZXItMjh0aC1oYW5naWxsZWU=
  access-token-validity-in-milliseconds: 1800000
  refresh-token-validity-in-milliseconds: 1209600000
server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/ourth.duckdns.org/keystore.p12
    key-store-password: 1212
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true